#!/usr/bin/env python3
"""
eyelaw -- FR194's L-1/L-2/L-3: are the nine per-message offsets b_m, or the
five determined indicator plaintexts p0_m, generated by a simple law over
corpus-internal message metadata? And is the b-vector structured at all?

EYESPIRAL-C, FR195 cycle. Read-only. stdlib only. Errors carry XD-MBYG04K-URS3LF.

WHY THIS EXISTS. FR30/36/53 killed every scale-invariant channel to the drift.
What survives is magnitude: the corpus now determines TWO relative vectors --
all 36 base differences (FR178) and five indicator plaintext differences
(FR192) -- and a law tying either to known metadata with a natural coefficient
pins the drift outright. FR166's assumption 3 (the +/-29 clustering) has sat
unpriced for 28 cycles; this instrument prices it.

PRE-REGISTRATION (declared before any corpus statistic below was computed):

  TIER 1 (law detection, scale-free): b_m = rho*f(m) + c. Test: over all
    informative unordered pairs, rho = D_b/D_f must be a single value mod 83,
    and every zero-D_f pair must have zero D_b. HIT = single rho over >=3
    informative pairs. Chance of a false hit ~ 83^-(k-1), k = informative
    pairs; any hit on this corpus is real.
  TIER 2 (natural coefficient, pins d): b_true = f exactly. Since
    b_true = d * b1 (drift-1 units), test d = D_f * D_b1^-1 single-valued.
  CATALOG for b (F-laws) and p0 (G-laws): index (canonical / East-first),
    length, cumulative start offset (continuous keystream), indicator glyph
    value c0, triplet index, East/West flag, slot-in-triplet, and the joint
    law p0 ~ b (L-3). Header value excluded: c[m][1] identical across all
    nine messages (verified from corpus.json), so it cannot discriminate.
  STRUCTURE PRICING (generic, not tuned to any observed pattern):
    S1: D = #distinct among the 36 folded pair differences r = min(x, 83-x)
    S2: Z = #zero differences among the 36
    Null: 1e6 iid-uniform 9-vectors mod 83. p1 = P(D <= D_real),
    p2 = P(Z >= Z_real). Bonferroni x2. Declared verdict bands:
    p < 0.0025 raw (0.005 corrected) ESTABLISHED; < 0.05 SUGGESTIVE; else NULL.
  KNOWN POST-HOC CAVEAT: the +/-29 / +1 / zero patterns were noticed on the
    8 published values before W2 was recovered; S1/S2 are generic statistics
    chosen to be pattern-agnostic, and the caveat travels with the result.
  HELD-OUT RECORD: the per-triplet-West-offset law predicted b[W2] = b[W3]
    = 23 (with ladder variants 22/24) BEFORE W2's recovery. Scored below.

DATA PROVENANCE (drift-1 units, gauge b[E1] = 0):
  FR32  (atlas tier)     : W1-E1=0, E2-E1=77, E5-E4=0, W4-E4=54, W3-E3=54
  FR192 (extended tier)  : E3-E1=52, W3-E1=23 (cross-checks FR32 OK), E4-E1=53
  FR178 (forced column)  : W2-E1=39; column validated on E2-E1=77, E3-E1=52
  p0 relative (FR192)    : E1=0, E2=63, E3=54, W3=30, E4=23
  c0, lengths            : verified against corpus.json this run
  W2's value is single-sourced (FR178 diagnostic table); flagged for
  canonical re-extraction on the extended builder. Everything else is
  double-sourced or closure-checked.
"""
import itertools, random, sys, os, json

XD = "XD-MBYG04K-URS3LF"; N = 83
MSGS = ["East 1","West 1","East 2","West 2","East 3","West 3","East 4","West 4","East 5"]

# ---------------------------------------------------------------- data
B1 = {"East 1":0,"West 1":0,"East 2":77,"West 2":39,"East 3":52,
      "West 3":23,"East 4":53,"West 4":24,"East 5":53}          # drift-1 units
P0 = {"East 1":0,"East 2":63,"East 3":54,"West 3":30,"East 4":23} # drift-1 units
C0 = {"East 1":50,"West 1":80,"East 2":36,"West 2":76,"East 3":63,
      "West 3":34,"East 4":27,"West 4":77,"East 5":33}
LEN = {"East 1":99,"West 1":103,"East 2":118,"West 2":102,"East 3":137,
       "West 3":124,"East 4":119,"West 4":120,"East 5":114}

PUBLISHED_DIFFS = [  # (m2, m1, value) meaning b[m2]-b[m1] = value at drift 1
    ("West 1","East 1",0),("East 2","East 1",77),("East 5","East 4",0),
    ("West 4","East 4",54),("West 3","East 3",54),           # FR32
    ("East 3","East 1",52),("West 3","East 1",23),("East 4","East 1",53), # FR192
    ("West 2","East 1",39),                                   # FR178
]

def cumoff():
    c, out = 0, {}
    for m in MSGS: out[m] = c % N; c += LEN[m]
    return out

F_LAWS = {  # b-vector catalog
    "F1 canonical index": {m:i for i,m in enumerate(MSGS)},
    "F2 East-first index": {"East 1":0,"East 2":1,"East 3":2,"East 4":3,"East 5":4,
                            "West 1":5,"West 2":6,"West 3":7,"West 4":8},
    "F3 message length": LEN,
    "F4 cumulative offset": cumoff(),
    "F5 indicator value c0": C0,
    "F6 triplet index": {"East 1":0,"West 1":0,"East 2":0,"West 2":1,"East 3":1,
                         "West 3":1,"East 4":2,"West 4":2,"East 5":2},
    "F7 East/West flag": {m:(1 if m.startswith("W") else 0) for m in MSGS},
    "F8 slot in triplet": {"East 1":0,"West 1":1,"East 2":2,"West 2":0,"East 3":1,
                           "West 3":2,"East 4":0,"West 4":1,"East 5":2},
}
TIER2_F = ["F3 message length","F4 cumulative offset","F5 indicator value c0",
           "F1 canonical index"]
G_LAWS = {  # indicator catalog (restricted to P0's five messages)
    "G1 p0 ~ c0": C0, "G2 p0 ~ length": LEN,
    "G3a p0 ~ canonical index": F_LAWS["F1 canonical index"],
    "G3b p0 ~ East-first index": F_LAWS["F2 East-first index"],
    "G4 p0 ~ b (joint, L-3)": B1,
}
TIER2_G = ["G1 p0 ~ c0","G2 p0 ~ length"]

# ---------------------------------------------------------------- engine
def inv(x): return pow(x % N, -1, N)

def tier1(vec, f):
    """single-rho ratio consistency; returns (verdict, detail)."""
    rhos, k = set(), 0
    for a, b in itertools.combinations(sorted(vec), 2):
        df, dv = (f[a]-f[b]) % N, (vec[a]-vec[b]) % N
        if df == 0:
            if dv != 0: return ("REFUTED", "zero-Df pair with nonzero Db")
            continue
        k += 1; rhos.add(dv * inv(df) % N)
    if k < 3: return ("UNDERDETERMINED", f"{k} informative pairs")
    return (("HIT", f"rho={rhos.pop()} over {k} pairs") if len(rhos) == 1
            else ("REFUTED", f"{len(rhos)} distinct rho over {k} pairs"))

def tier2(vec1, f):
    """b_true = f exactly: d = Df * Db1^-1 single-valued; returns verdict."""
    ds, k = set(), 0
    for a, b in itertools.combinations(sorted(vec1), 2):
        df, dv = (f[a]-f[b]) % N, (vec1[a]-vec1[b]) % N
        if dv == 0:
            if df != 0: return ("REFUTED", "zero-Db1 pair with nonzero Df")
            continue
        k += 1; ds.add(df * inv(dv) % N)
    if k < 3: return ("UNDERDETERMINED", f"{k} informative pairs")
    if len(ds) == 1:
        d = ds.pop()
        return (("HIT", f"d={d} over {k} pairs") if d != 0
                else ("REFUTED", "d=0"))
    return ("REFUTED", f"{len(ds)} distinct d over {k} pairs")

def fold(x): x %= N; return min(x, N - x)

def stats(vec):
    ds = [fold(vec[a]-vec[b]) for a, b in itertools.combinations(sorted(vec), 2)]
    return len(set(ds)), sum(1 for x in ds if x == 0)

# ---------------------------------------------------------------- gates
def gates():
    ok = True
    def chk(name, cond, note=""):
        nonlocal ok; ok &= bool(cond)
        print(f"  [{'PASS' if cond else 'FAIL'}] {name} {note}")
    # G1 planted tier-1 law is found, and only by its own f
    plant = {m: (7*LEN[m] + 3) % N for m in MSGS}
    hits = [nm for nm, f in F_LAWS.items() if tier1(plant, f)[0] == "HIT"]
    chk("planted rho=7 length-law detected, uniquely", hits == ["F3 message length"],
        f"(hits: {hits})")
    # G2 shuffled-f rejection
    rng = random.Random(4194); false = 0
    vals = [LEN[m] for m in MSGS]
    for _ in range(500):
        sh = vals[:]; rng.shuffle(sh)
        if tier1(plant, dict(zip(MSGS, sh)))[0] == "HIT": false += 1
    chk("shuffled-f false-hit rate 0/500", false == 0, f"({false}/500)")
    # G3 planted tier-2 recovers d
    d = 37; b1 = {m: (LEN[m]-LEN["East 1"]) * inv(d) % N for m in MSGS}
    v, det = tier2(b1, LEN)
    chk("planted tier-2 recovers d=37", v == "HIT" and "d=37" in det, f"({det})")
    # G4 corruption refutes
    bad = dict(plant); bad["West 4"] = (bad["West 4"]+1) % N
    chk("one corrupted value kills the law",
        tier1(bad, F_LAWS["F3 message length"])[0] == "REFUTED")
    # G5 statistic sanity
    Dp, _ = stats(plant); Du, _ = stats({m: rng.randrange(N) for m in MSGS})
    chk("MC statistic separates plant from uniform draw", Dp < Du, f"(D {Dp} vs {Du})")
    # G6 assembled vector reproduces every published difference
    bad = [(m2, m1, v) for m2, m1, v in PUBLISHED_DIFFS
           if (B1[m2]-B1[m1]) % N != v % N]
    chk("b-vector reproduces all 9 published diffs", not bad, f"(fail: {bad})")
    # G7 corpus cross-check when available
    cj = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "..", "Eyes-main", "noita_eye_core", "corpus.json")
    if os.path.exists(cj):
        c = json.load(open(cj)); rows = dict(zip(c["message_labels"], c["ciphertexts"]))
        chk("c0/lengths match corpus.json",
            all(rows[m][0] == C0[m] and len(rows[m]) == LEN[m] for m in MSGS))
        chk("stamped header uniform (c1 identical x9) -> header laws excluded",
            len({rows[m][1] for m in MSGS}) == 1)
    if not ok: raise SystemExit(f"{XD}: GATE FAILURE -- results below are void")
    print("  gates: ALL GREEN")

# ---------------------------------------------------------------- run
def main():
    print("eyelaw -- pre-registered law sweep over b (36 pairs) and p0 (10 pairs)")
    print("selftest gates:"); gates()

    print("\nHELD-OUT SCORE -- the pattern's simplest law, fixed before W2 arrived:")
    pred = {"primary b[W2]=23": 23, "ladder 22": 22, "ladder 24": 24}
    for k, v in pred.items():
        print(f"  {k:22s} observed {B1['West 2']:2d}  ->  "
              f"{'CONFIRMED' if B1['West 2']==v else 'REFUTED'}")

    print("\nTIER 1 -- b_m = rho*f(m) + c  (scale-free law detection):")
    for nm, f in F_LAWS.items():
        v, det = tier1(B1, f); print(f"  {nm:26s} {v:15s} {det}")
    print("TIER 2 -- b_true = f exactly (a hit pins the drift):")
    for nm in TIER2_F:
        v, det = tier2(B1, F_LAWS[nm]); print(f"  {nm:26s} {v:15s} {det}")

    print("\nTIER 1 -- p0_m = rho*g(m) + c  (five messages, 10 pairs):")
    for nm, f in G_LAWS.items():
        sub = {m: f[m] for m in P0}
        v, det = tier1(P0, sub); print(f"  {nm:26s} {v:15s} {det}")
    print("TIER 2 -- p0_true = g exactly (a hit pins the drift):")
    for nm in TIER2_G:
        sub = {m: G_LAWS[nm][m] for m in P0}
        v, det = tier2(P0, sub); print(f"  {nm:26s} {v:15s} {det}")

    Dr, Zr = stats(B1)
    print(f"\nSTRUCTURE PRICING -- real b-vector: D={Dr} distinct folded diffs, "
          f"Z={Zr} zeros (of 36)")
    rng = random.Random(83); T = 1_000_000; le = ge = 0
    for _ in range(T):
        D, Z = stats({m: rng.randrange(N) for m in MSGS})
        le += (D <= Dr); ge += (Z >= Zr)
    p1, p2 = le/T, ge/T
    print(f"  null (1e6 iid-uniform 9-vectors): P(D<={Dr}) = {p1:.2e}   "
          f"P(Z>={Zr}) = {p2:.2e}")
    for nm, p in (("S1 distinct-diffs", p1), ("S2 zeros", p2)):
        band = ("ESTABLISHED" if p < 0.0025 else
                "SUGGESTIVE" if p < 0.05 else "NULL")
        print(f"  {nm:20s} raw p = {p:.2e}  x2 Bonferroni = {min(1,2*p):.2e}  "
              f"-> {band}")
    print("  (post-hoc caveat travels with S1/S2: see pre-registration block)")

if __name__ == "__main__":
    main()
